### ISSUE TITLE
Moderation plugin and Infraction system

### ISSUE THREAD

**Issue by Rage0001** [next/zeiw-issues#30]
Need to make a proper moderation plugin with essential moderation commands.
To go with it, is needed an infraction system which will store every action in a database and make those actions fetchable for normal users through the bot.

- [ ] Create a database instance to store infractions
- [ ] Create schema for infractions
- [ ] Create all necessary functions and commands for moderation plugin
- [ ] Create a way to display infractions

**Comment by pnfcre** [comment]
Closing due to low priority & inactivity, can be reopened at any time! 👍
