### ISSUE TITLE
Failed to set faction

### ISSUE THREAD

**Issue by pnfcre** [next/zeiw-issues#49]
## Short Description

Error: Failed to set faction when trying to change faction

## Expected Result

Facation should be changed

## Actual Result

Facation is not changed

## Steps to Reproduce

Step 1: Sign in with Discord.
Step 2: Open up your profile.
Step 3: Hit "Choose Faction".
Step 4: Choose any faction.

## Client Settings

```
[node] 12.4.0
[chrome] 76.0.3809.126
[electron] 6.0.3
[ZEIW] 232f21ec34b1a07bf4441c14c81ff71f2f2b05d2
```

## System Settings

```
Windows 10 OS Version 1809 (Build 17763.615)
```

**Comment by Mippy** [comment]
Fixed
