### ISSUE TITLE
Ability to change accent colors

### ISSUE THREAD

**Issue by runic-tears** [next/zeiw-issues#54]
Hey-hey! I thought that it'd be pretty cool if there was an ability to change colors of the whole game, e.g. replace blue with purple and orange with white, so it would look like that:

![zeiw-desktop_offbCWQFMc](https://user-images.githubusercontent.com/51153795/65520575-db0f9d00-def8-11e9-9734-525444d0a77e.png)

**Comment by pnfcre** [comment]
Sounds like a great idea, I'll definitely look at it!
