### ISSUE TITLE
The squares loading animation being shown in the front view when opening Customization Settings

### ISSUE THREAD

**Issue by runic-tears** [next/zeiw-issues#55]
## Short Description
The "squares" loading animation shows on the customization settings modal

## Expected Result
The "squares" animation should be in a background, behind the customization modal window

## Actual Result
The "squares" loading animation is being shown on the front view

## Steps to Reproduce

Step 1: Click "Host Party"
Step 2: Now go to settings
Step 3: Click "Customization"
Step 4: Observe it!

## Client Settings
canary@6f71f5c

## System Settings
Windows 10 Pro (1903)

## 📎 Attachments
![](https://media.defracted.net/1e2MuzS.png)

**Comment by Mippy** [comment]
👍
