### ISSUE TITLE
Option to choose 3D game play.

### ISSUE THREAD

**Issue by No3Mc** [next/zeiw-issues#60]
After googling for a while:
A game founded by Ted Dabney in 1973 for Atari.
I found pong museum's gameplay(3D pong):
https://www.youtube.com/watch?v=y2j2IywzaqA
Option to play game in 3D mode/regular mode.
Why 3D mode?
1- It will add more impressive details to the game.
2- Game's going to be more addictive for both the viewers and players.

**Comment by pnfcre** [comment]
Thanks for the suggestion! We however do not have enough resources to implement this feature, therefore we're closing this issue. This does not mean that your idea isn't good - it certainly is!
