### ISSUE TITLE
Button is unthemed.

### ISSUE THREAD

**Issue by techdude1-dev** [next/zeiw-issues#63]
## Short Description
The button is unthemed.

## Expected Result
Button should be round and go with the theme.
Button is not themed

Steps to Reproduce
Go https://zeiw.me/ and scroll all the way down and see the light and dark theme button. Notice how it is unthemed.
![image](https://user-images.githubusercontent.com/52178694/66942212-6c0bfc80-effd-11e9-8e59-f375d56506d8.png)

## Client Settings
Chrome OS

## System Settings
Chrome OS

**Comment by techdude1-dev** [comment]
The button also does not go with the theme. 
![image](https://user-images.githubusercontent.com/52178694/66942484-0a985d80-effe-11e9-9b70-e3325ca8573b.png)

**Comment by pnfcre** [comment]
Intended behavior, sorry.
