### ISSUE TITLE
Creating multiple tabs will increase the online player count when signed in.

### ISSUE THREAD

**Issue by techdude1-dev** [next/zeiw-issues#64]
## Short Description
Creating multiple tabs will increase the online player count when signed in.
## Expected Result
Not boost the online player count when signed in.
## Actual Result
Boots the online player count when having multiple tabs open.
## Steps to Reproduce

Step 1: Go to https://play.zeiw.me/#
Step 2:  Sign with Discord.
Step 3: Open 4 tabs
Step 4: Notice how the player count is boosted up.
![image](https://user-images.githubusercontent.com/52178694/66942990-1d5f6200-efff-11e9-8191-972988689192.png)

## Client Settings
Chrome OS
## System Settings
canary@655eb60

**Comment by pnfcre** [comment]
Hi there,

Once again, thanks for the report - but this is unfortunately intended behavior! Our current definition of "online" is "amount of sessions connected to the websocket". If you'd like to change this, please submit a FR.

Kind regards,
Casper.
