### ISSUE TITLE
Change the way how to online player count is defined.

### ISSUE THREAD

**Issue by techdude1-dev** [next/zeiw-issues#65]
If you were to sign in with discord and open multiple tabs of https://play.zeiw.me/ it would boost the online player amount. I would like to have this changed because it shows an inaccurate amount of people online when you have multiple tabs open. 
![image](https://user-images.githubusercontent.com/52178694/66943613-6532b900-f000-11e9-9e27-b42a1f1ebaf2.png)

**Comment by pnfcre** [comment]
I've deployed a change where "online" is changed to "connected" - should make more sense!

**Comment by pnfcre** [comment]
Changes should be live in a minute :tada:
