### ISSUE TITLE
Questioning the Win???

### ISSUE THREAD

**Issue by techdude1-dev** [next/zeiw-issues#66]
## Steps to Reproduce

Step 1: Win a game.
Step 2: Observe the Win Modal
Step 3: See how there is a question mark above the "You Win" text.
![image](https://user-images.githubusercontent.com/52178694/67110842-80c8cb80-f188-11e9-9259-89a5365e08f5.png)

## Client Settings
canary@49fb049

## System Settings
Chrome OS

**Comment by pnfcre** [comment]
This is technically not a bug, it's intended - but I understand the confusion. Therefore, I'll be implementing a "fix" ASAP.

**Comment by pnfcre** [comment]
![image](https://user-images.githubusercontent.com/24176136/67114623-a8498380-f1dc-11e9-8a50-6d3d5e7eac1e.png)
![image](https://user-images.githubusercontent.com/24176136/67114637-b1d2eb80-f1dc-11e9-8c6c-01e9147a87fb.png)
