### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by techdude1-dev** [next/zeiw-issues#87]
It would be nice if we could get the game visually themed to the current season. Like for this season maybe put a ghost or some spooky animation in the game.

**Comment by techdude1-dev** [comment]
@pnfcre Could you please take a look at this? I have not gotten a response from the developer team about this.

**Comment by pnfcre** [comment]
Hi there, we currently don't have enough resources to implement this, but we might re-open it in the future. Thanks for the feedback! 👌
