### ISSUE TITLE
Unable to sign into discord

### ISSUE THREAD

**Issue by techdude1-dev** [next/zeiw-issues#88]
## Steps to Reproduce

Step 1: Open chrome
Step 2: Go into incognito tag 
Step 3: Go here 
![image](https://user-images.githubusercontent.com/52178694/69027262-2a1b0100-0983-11ea-92ce-ceb583eacd3f.png)

Step 4: Log into discord
Step 5: Observe how it takes you to servers not oauth

**Comment by pnfcre** [comment]
CNR. Please open DevTools and run `localStorage.clear()` and then hard refresh the page and try again.

**Comment by Mippy** [comment]
Probably actually a Discord bug.

https://github.com/discordapp/discord-api-docs/issues/421

**Comment by Mippy** [comment]
yeah its fixed now https://github.com/discordapp/discord-api-docs/issues/1187
