### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by techdude1-dev** [next/zeiw-issues#89]
Add more servers for lower ping. Also please make it so we can have more events with factions. Maybe find an event manager? Very much appreciated.
- Signed tech_dude1#0001 
User ID 503677457107517442 
Hypesquad Balance and Discord Nitro Member.

**Comment by pnfcre** [comment]
Closing in favor of #40, we should have a US server soon. We'll consider your last as well, thanks for your feedback! 🙏

**Comment by techdude1-dev** [comment]
@pnfcre Ok, Thank you for very fast response.
