### ISSUE TITLE
BETA

### ISSUE THREAD

**Issue by techdude1-dev** [next/zeiw-issues#92]
Make a BETA program so people can get early updates.
• Signed tech_dude1#0001
User ID 503677457107517442
Hypesquad Balance and Discord Nitro Member.

**Comment by pnfcre** [comment]
Hi there,

We value your feedback. We already have the Beta Features toggle in Game Settings that gives you access to any unreleased features!

Kind regards,
Casper.

**Comment by techdude1-dev** [comment]
What BETA features are there now?

**Comment by pnfcre** [comment]
None
