### ISSUE TITLE
Broken CDN Redirect URL

### ISSUE THREAD

**Issue by techdude1-dev** [next/zeiw-issues#93]
## Steps to Reproduce

Step 1: Go to https://cdn.zeiw.me/
Step 2: Then click "Back to site".
![image](https://user-images.githubusercontent.com/52178694/70831202-c4b20880-1da6-11ea-8ab7-26990d53b9c5.png)

Step 3: Observe how it redirects you back to https://cdn.zeiw.me/

**Comment by pnfcre** [comment]
Not a bug.

**Comment by techdude1-dev** [comment]
Why? Please explain.

**Comment by pnfcre** [comment]
the cdn is not supposed to redirect to the website

**Comment by techdude1-dev** [comment]
Then it should not show an error.

**Comment by pnfcre** [comment]
The error page is a built-in 404 page in Netlify's CDN. We cannot, and do not intend to, modify that page. A content delivery network has one job: to serve assets. Therefore, we don't serve any index page - hence the 404 error.
